root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "static", "dist", "node_modules"]
include_dir = ["cmd", "internal", "pkg", "config", "templates"]
exclude_file = []
log = "build-errors.log"
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true